# .air.toml

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ./cmd/app"
bin = "tmp/main.exe"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "node_modules"]

[log]
time = true
